from alembic import op
import sqlalchemy as sa
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_action_tokens_user_id'), 'action_tokens', ['user_id'], unique=False)
    op.create_table('calls',
    sa.Column('sid', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('number_id', sa.String(length=36), nullable=False),
    sa.Column('destination', sa.String(length=20), nullable=False),
    sa.Column('reserved_minutes', sa.Integer(), nullable=False),
    sa.Column('billed_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['numbers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['tenant_id'], unique=False)
    op.add_column('sessions', sa.Column('mfa_authenticated', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('tenants', sa.Column('billing_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.Text(), server_default='', nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('mfa_counter', sa.Integer(), server_default='-1', nullable=False))
    op.add_column('users', sa.Column('mfa_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'mfa_authenticated')
    op.drop_column('users', 'mfa_started_at')
    op.drop_column('users', 'mfa_counter')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'email_verified')
    op.drop_column('tenants', 'billing_checked_at')
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_action_tokens_user_id'), table_name='action_tokens')
    op.drop_table('action_tokens')
    op.drop_table('worker_heartbeats')
    op.drop_table('email_jobs')
    # ### end Alembic commands ###
