"""autonomy"""

from alembic import op
import sqlalchemy as sa

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("opens", sa.Integer(), nullable=False),
        sa.Column("closes", sa.Integer(), nullable=False),
        sa.Column("weekdays", sa.String(length=20), nullable=False),
        sa.Column("bookings_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=1000), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_knowledge_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bookings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=False),
        sa.Column("peer", sa.String(length=30), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "request_key"),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookings_starts_at"), ["starts_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bookings_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("number_id", sa.String(length=36), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("peer", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("assigned_to", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["number_id"],
            ["numbers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "number_id", "channel", "peer"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "action_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("confirmation_message_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("receipt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "request_key"),
    )
    with op.batch_alter_table("action_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_jobs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id"),
    )
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_leads_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("ai_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("automatic", sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table("ai_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("autonomous", sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column("paused", sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column("language", sa.String(length=20), server_default="en-GB", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_profiles", schema=None) as batch_op:
        batch_op.drop_column("language")
        batch_op.drop_column("paused")
        batch_op.drop_column("autonomous")

    with op.batch_alter_table("ai_jobs", schema=None) as batch_op:
        batch_op.drop_column("automatic")

    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_tenant_id"))

    op.drop_table("leads")
    with op.batch_alter_table("action_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_jobs_tenant_id"))

    op.drop_table("action_jobs")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_tenant_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bookings_starts_at"))

    op.drop_table("bookings")
    with op.batch_alter_table("knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_tenant_id"))

    op.drop_table("knowledge")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_tenant_id"))

    op.drop_table("departments")
    # ### end Alembic commands ###
