"""channels"""

from alembic import op
import sqlalchemy as sa

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("whatsapp_sender", sa.String(length=40), server_default="", nullable=False))
        batch_op.add_column(sa.Column("rcs_service_sid", sa.String(length=40), server_default="", nullable=False))
        batch_op.add_column(sa.Column("rcs_sender", sa.String(length=200), server_default="", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("numbers", schema=None) as batch_op:
        batch_op.drop_column("rcs_sender")
        batch_op.drop_column("rcs_service_sid")
        batch_op.drop_column("whatsapp_sender")

    # ### end Alembic commands ###
