"""integrations"""

from alembic import op
import sqlalchemy as sa

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("encrypted_config", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("integrations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_integrations_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider_id", sa.String(length=100), server_default="", nullable=False))

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("integration_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key("fk_department_integration", "integrations", ["integration_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint("fk_department_integration", type_="foreignkey")
        batch_op.drop_column("integration_id")

    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_column("provider_id")

    with op.batch_alter_table("integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_integrations_tenant_id"))

    op.drop_table("integrations")
    # ### end Alembic commands ###
