"""verified_identity"""

from alembic import op
import sqlalchemy as sa

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("preferences", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customers_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "identity_challenges",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("identity_challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_identity_challenges_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_bookings_customer_id"), ["customer_id"], unique=False)
        batch_op.create_foreign_key("fk_booking_customer", "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("customer_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_conversations_customer_id"), ["customer_id"], unique=False)
        batch_op.create_foreign_key("fk_conversation_customer", "customers", ["customer_id"], ["id"])

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sensitive_payload", sa.Text(), server_default="", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_column("sensitive_payload")

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_constraint("fk_conversation_customer", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_conversations_customer_id"))
        batch_op.drop_column("customer_id")

    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_booking_customer", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_bookings_customer_id"))
        batch_op.drop_column("customer_id")

    with op.batch_alter_table("identity_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_challenges_tenant_id"))

    op.drop_table("identity_challenges")
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customers_tenant_id"))

    op.drop_table("customers")
    # ### end Alembic commands ###
