"""operations_controls"""

from alembic import op
import sqlalchemy as sa

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_api_keys",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("scopes", sa.String(length=100), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
        sa.UniqueConstraint("id"),
    )
    with op.batch_alter_table("customer_api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customer_api_keys_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "financial_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "reference"),
    )
    with op.batch_alter_table("financial_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_financial_entries_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("knowledge_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_id"],
            ["knowledge.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_id", "version"),
    )
    with op.batch_alter_table("knowledge_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_knowledge_revisions_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("knowledge_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_revisions_tenant_id"))

    op.drop_table("knowledge_revisions")
    with op.batch_alter_table("financial_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_entries_tenant_id"))

    op.drop_table("financial_entries")
    with op.batch_alter_table("customer_api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_api_keys_tenant_id"))

    op.drop_table("customer_api_keys")
    # ### end Alembic commands ###
